import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/config";
import { buildEnergyTrend } from "@/lib/energy";

const DEFAULT_DAYS = 30;

/**
 * GET /api/energy/trend?days=30
 *
 * Reads the cached `score` of each EnergyEntry, so 30 days cost one query instead of
 * 30 rebuilds. `insights` are computed, never generated by AI: a pillar shows up only
 * when it differs by more than 20 percentage points between bad days (felt <= 5) and
 * good ones (felt >= 8), and only after 5 rated days.
 */
export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const raw = Number(req.nextUrl.searchParams.get("days"));
  const days = Number.isFinite(raw) && raw > 0 ? raw : DEFAULT_DAYS;

  try {
    const trend = await buildEnergyTrend(session.user.id, days);
    return NextResponse.json(trend);
  } catch (err) {
    console.error("[api/energy/trend] GET nie powiodlo sie:", err);
    // An empty but valid shape beats an error screen on a chart the user just opened.
    return NextResponse.json({
      days: [],
      averages: { total: 0, pillars: {} },
      weakest: null,
      insights: [],
      note: "Nie udało się wczytać trendu. Spróbuj ponownie za chwilę.",
    });
  }
}
